#request

# Local database path on which rtabmap is running.
# If the path doesn't exist, a new database will be created.
string database_path

# If the database already exists, data will be cleared if true.
bool clear

---
#response, return false on rtabmap initialization failure.