# Get a plan from the current position to the goal node or pose 

# The final node of the goal (set 0 to use pose instead)
int32 goal_node
# The final pose of the goal position (used only if goalNodeId=0)
geometry_msgs/PoseStamped goal

# How many meters from the map's graph we can plan (0=infinite)
float32 tolerance
---
Path plan