
name: ros2

on:
  push:
    branches: [ lyrical-devel ]
  pull_request:
    branches: [ lyrical-devel ]

env:
  BUILD_TYPE: Release

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    name: Build ros2 ${{ matrix.ros_distro }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros_distro: [lyrical]
        include:
        - ros_distro: lyrical
          skip_keys: '' # skip keys shoudl be empty when release on ROSDISTRO_devel branch, comment these keys in the appriopriate package.
          # rtabmap_costmap_plugins cannot be built, missing nav2 on lyrical, commented from rtabmap_ros package. 
          # Make sure rosdistro doesn't declare rtabmap_costmap_plugins.
          packages: 'rtabmap_ros'
      fail-fast: false
    container:
      image: osrf/ros:${{ matrix.ros_distro }}-desktop-full
    steps:   
    - uses: actions/checkout@v4
    - uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: ${{ matrix.ros_distro }}
    - run: |
        DEBIAN_FRONTEND=noninteractive
        sudo apt update
        sudo apt upgrade -y
    - run: |
        echo "repositories:\n  introlab/rtabmap:\n    type: git\n    url: https://github.com/introlab/rtabmap.git\n    version: lyrical-devel\n" > /tmp/deps.repos &&\
        cat /tmp/deps.repos
    - uses: ros-tooling/action-ros-ci@v0.4
      with:
        package-name: ${{ matrix.packages }}
        target-ros2-distro: ${{ matrix.ros_distro }}
        vcs-repo-file-url: /tmp/deps.repos
        rosdep-check: true
        rosdep-skip-keys: "${{ matrix.skip_keys }}"
